/// Flutter icons MyEmployeeApp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyEmployeeApp
///      fonts:
///       - asset: fonts/MyEmployeeApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyEmployeeApp {
  MyEmployeeApp._();

  static const _kFontFam = 'MyEmployeeApp';
  static const String? _kFontPkg = null;

  static const IconData arrow_right_alt_fill0_wght500_grad0_opsz24_14 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_fill0_wght400_grad0_opsz24_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event_fill0_wght300_grad0_opsz24__1__1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_fill0_wght300_grad0_opsz24__2__1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plusicon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work_fill0_wght300_grad0_opsz24_1 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_drop_down_fill1_wght400_grad0_opsz24_3 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
